### ISSUE TITLE
Sample rate is affected by the locale 

### ISSUE THREAD

**Issue by Aramack** [DataDog/php-datadogstatsd#126]
We recently noticed that we were seeing this error in our agent logs:
```
2022-05-19 19:07:59 UTC | CORE | ERROR | (pkg/dogstatsd/server.go:592 in errLog) | Dogstatsd: error parsing metric message '"global_method:********@0,5|#env:prod': could not parse dogstatsd sample rate "@0,5"
```
We traced this back to the fact that these dogstatsd metrics were being emitted from an application using the de_DE local. This can be reproduced with the following snippet:
```
setlocale(LC_ALL, 'de_DE');
$statsd = new \DataDog\DogStatsd(
    array('host' => '127.0.0.1',
          'port' => 8125,
     )
  );
$statsd->gauge('with.locale', 200, 0.1);
```

The metric emitted by this script will be:
`with.locale:200|g|@0,1`
Where the decimal place is replaced with a comma. The agent is unable to process this number. This appears to be similar to the problem described in https://github.com/DataDog/php-datadogstatsd/pull/100, but with the sample rate instead of the metric itself.

**Comment by gh123man** [comment]
I posted a fix https://github.com/DataDog/php-datadogstatsd/pull/128
Can you let me know if this looks good to you?

**Comment by Aramack** [comment]
Looks fine for my use case.
