### ISSUE TITLE
Please look at the pull requests and merge or reject them.

### ISSUE THREAD

**Issue by iparq** [DataDog/php-datadogstatsd#19]
At least the pwillcode one which fixes the composer package psr-0 autoloading.  I am using that fork in production now specifically because of the autoloading.

Thanks.

**Comment by remh** [comment]
Hey @iparq . You're right we got behind on this repo.

We're going to take a pass at those.

Thanks for the feedback!

**Comment by nortron** [comment]
:+1:

**Comment by nortron** [comment]
For those coming here to get autoloading from this library you can add the following to your composer.json until the fork is merged in:

```
  "autoload": {
    "files": ["vendor/datadog/php-datadogstatsd/libraries/datadogstatsd.php"]
  }
```

**Comment by elafarge** [comment]
The PR have been merged. Many thanks to all contributors ! 

A new version of php-datadogstatsd has been released on packagist : https://packagist.org/packages/datadog/php-datadogstatsd
