### ISSUE TITLE
Bring up to date with lsjroberts/datadog-statsd fork.

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/php-datadogstatsd#3]
There's been a bunch of updates in this fork (https://github.com/lsjroberts/datadog-statsd) that would be nice to get into our version, including a bunch of cleanup and refactoring.

@clutchski Can you take a look at the fork when you get a chance and see if it's worth merging back into ours?

**Comment by enorton** [comment]
I agree. This should be brought up to snuff with the lsjroberts fork. Especially if this it to the be official php library for Datadog.

**Comment by jmkgreen** [comment]
This still relevant? Ticket is three years old and original reference has moved on....
