### ISSUE TITLE
Integration with Laravel 5.1

### ISSUE THREAD

**Issue by isbkch** [DataDog/php-datadogstatsd#33]
I was looking for an easy way to integrate it with Laravel 5.1 but couldn't find facade or service provider shipped with it. Is there any plans to add those in the futur ?

**Comment by aligajani** [comment]
@isbkch  You can make your own Package.

**Comment by chaseconey** [comment]
Here is a package that I made with pretty basic functionality:
https://github.com/chaseconey/laravel-datadog-helper

**Comment by jeremy-lq** [comment]
Thanks for the contribution @chaseconey! Closing this as the linked package should address the original issue.
