### ISSUE TITLE
PSR1, 2 and 4 compliance

### ISSUE THREAD

**Issue by onema** [DataDog/php-datadogstatsd#36]
This project has a combination of different styles. I suggest using [PSR-1: basic coding standard](http://www.php-fig.org/psr/psr-1/), [PSR-2: coding style guide](http://www.php-fig.org/psr/psr-2/), and [PSR-4: autoloading standard](http://www.php-fig.org/psr/psr-4/). 

See the [this fork](https://github.com/onema/php-datadogstatsd/tree/develop/src) for a sample of how this code would look like. 

also check out [The PHP Coding Standards Fixer](http://cs.sensiolabs.org/)

Regards,

**Comment by irabinovitch** [comment]
@onema Thanks for the feedback and your efforts here.  Since it looks like you've started down this path, do you want to go ahead and open a PR with those changes? Thanks!

**Comment by hush-hush** [comment]
This issue should, finally, be resolved with #50. Feel free to reopen it if needed.

Thanks again !
