### ISSUE TITLE
Events should be set over UDP to the DD agent 

### ISSUE THREAD

**Issue by onema** [DataDog/php-datadogstatsd#37]
The current implementation of the `event` method uses the API to send events over HTTP, this can take a toll in the overall performance of an application that sends large number of events to DataDog. API events should be separated from their `dogstatsd` counterpart or removed. 

The implementation of this method should send events to the DataDog agent over UDP.

**Comment by hush-hush** [comment]
Hi @onema,

Thanks for opening this issue, and sorry it took us so long to answer. Since #41 was merged it's possible to send events over UDP.
