### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by vanderlee** [DataDog/php-datadogstatsd#47]
This library seems to be lagging a few significant PR's.
Is it still being maintained or is it abandoned?

**Comment by jeremy-lq** [comment]
@vanderlee (and anyone else using php-datadogstatsd). We haven't done a good job maintaining this repository, and for that we apologize. We'll review the pending PRs and issues ASAP, and are taking steps to ensure our open source repositories don't languish in this manner moving forward. Thanks for the patience.
