### ISSUE TITLE
Link to Laravel Wrapper

### ISSUE THREAD

**Issue by chaseconey** [DataDog/php-datadogstatsd#55]
Hello there,

I was wondering if you would be interested in adding my library to the bottom of the README here. It's a wrapper around this library, but made specifically for the Laravel framework. I have already included a couple links to this library, and I think it would be cool if it was cyclical. It has been stable for several months and is definitely ready for production use.

https://github.com/chaseconey/laravel-datadog-helper

Please let me know what other information you might need.

Thanks!

**Comment by masci** [comment]
@chaseconey happy to link your work from the README, can you open a PR for that?

**Comment by chaseconey** [comment]
@masci I have added a PR and linked above.

Thanks!

**Comment by masci** [comment]
Merged, thanks!
