### ISSUE TITLE
submit to packagist.org

### ISSUE THREAD

**Issue by cornernote** [DataDog/php-datadogstatsd#7]
Hello,

I noticed you have a composer.json in your repo, but the package has not been submitted to packagist.org.

It would be great if you can submit it, then it can be easily used as a composer package.
http://packagist.org/packages/submit

Or perhaps I am missing something?

Thanks.

**Comment by joawan** [comment]
:+1:

**Comment by nebkam** [comment]
:+1:

**Comment by ava-paulw** [comment]
:+1:

**Comment by remh** [comment]
Thanks for the feedback everyone, we'll do this shortly.

**Comment by hkaj** [comment]
Thank you all for your patience, you can now find the package on packagist.org: https://packagist.org/packages/datadog/php-datadogstatsd
